---
title: "Introduction to Git and GitHub"
author:
    - name: "Julen Astigarraga & Verónica Cruz-Alonso"
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate
        code_folding: false  
        toc: true            
        toc_depth: 3
        css: styles.css         
editor_options: 
  chunk_output_type: console
---

Don't panic if you think git and github is confusing and not very intuitive. People who have been using them for many years think so too. Here we try to explain in a simple way the basic principles of git and github and how to solve common problems.

# [Download Git](https://git-scm.com/downloads)

# [Register for a GitHub account](https://github.com)

# Create a repository

## From GitHub

-   `New or +`: create a remote repository
-   `Code` and copy the https path
-   Create a new project in R selecting version control and copy the link from the GitHub repository previously created

`r emo::ji("voltage")` *Keep in mind that there are a million different ways to do the same thing in git but we explain here the ones we find easiest or the ones we are most used to*

## From Git

-   `git --help`: help (note that the em-dash are actually two dashes in the terminal)
-   `cd \~/Desktop`: create the repo in the desktop
-   `mkdir git_session`: make a directory named git_session
-   `cd "git_session"`: move inside the folder named git_session
-   `git init`: initialise an empty git repository
-   `cd ..`: go backwards in the path. If you are going to create a new repository is important to go backwards. It's not a good idea to create a repository inside a repository
-   `git remote add origin <https://github.com/>...`: set a remote branch

# Workflow in Git

Three trees:

1.  Working directory: where you are working. This tree is synchronised with the local files on your pc.
2.  Staging area: intermediate area between the working directory and the local repository. It records the changes you specify in your directory. Also called Index.
3.  Local repository: this is where all the changes are stored on your pc. Also called HEAD.

# Status

-   `ls`: show the files that are in the repository
-   `ls -a`: show all the files that are in the repository (also the hidden ones)
-   `git status`: show the status of the working directory and the staging area. It allows you to see which changes are staged, which are not, and which files are not being tracked by Git
-   `pwd`: in which directory you are

# Git add

-   git add: add a change from the working directory to the staging area (i.e., snapshot). It tells Git that you want to include updates to some file in the next commit. However, git add doesn't really affect the local repository in any meaningful way. The changes aren't saved until the git commit is executed

    -   `git add .`: record all changes at once
    -   `git add filename.txt`: record all changes to the file named filename.txt for the next commit

# Git commit

A git commit is like a snapshot of the code. Every `git commit` has a SHA (Secure Hash Algorithm) which is something like this: 1d21fc5c33cddc6beb7823400b9c7c6bc2804be4. It seems difficult to understand but don't worry you just need to remember the first six digits 1d21fc `r emo::ji("shocked")` (kidding). With the SHA you can see the changes that were made in that commit. If something happens that part is saved so you can easily go back there.

You may have already noticed that following this logic each commit has a parent commit that you can easily go to with the SHA or HEAD

-   git commit: save the changes to the local repository

    -   `git commit -m "short and descriptive commit message"`
    -   `git show SHA`: changes made in that commit. The first 6 digits of the SHA are enough to show the changes
    -   `git diff`: show unstaged changes (changes not added with `git add`)
    -   `git diff --staged`: show staged changes (changes added with `git add`)
    -   `git diff \--HEAD`: show unstaged and staged changes
    -   `git diff \--color-words`: a different way to getting the output of git diff
    -   `git diff \--stat`: summary of which files were changed & number of added and deleted lines
    -   `git log`: the commit history
    -   `git log -1`: show the latest commit
    -   `git log \--oneline`: show all the commit history in one line
    -   `git diff HEAD\~1 filename.txt`: go one step backwards and show changes since then. HEAD is a pointer to the commit. So you can see the current commit `git show HEAD` or show 100 commits ago `git show HEAD~100`
    -   `git checkout 45d2210 filename.txt`: go back to that commit -- consider just using the first 7 numbers of the identifier
    -   `git checkout HEAD filename.txt`: go to the latest commit
    -   `git commit \--amend -m "message"`: change the message of the last commit
    -   `git commit \--amend \--no-edit`: add a change after a commit. Remember to `git add` first
    -   `git rm \--cached filename`: remove a file from Git's index. Very useful if you have committed a 10GB file (we have all done this `r emo::ji("wink")`)

# Git reset & git revert

-   `git reflog`: track when Git refs were updated in the local repository.

-   `git reset`: undo a git commit or/and a git add

    -   `git reset \--mixed HEAD\~1`: reset the commit and the records but not the changes made to the working directory. It is equivalent to `git reset`. The HEAD\~1 means the commit before the head. You can go one commit back, two, etc.
    -   `git reset \--hard HEAD\~1`: reset the records and all changes made to the working directory. `r emo::ji("danger")` *This is the most DANGEROUS option. Note that it deletes uncommitted changes and points your branch to the specified commit. We recommend to run `git status` first and see if there are any uncommitted changes. If there are save them with `git stash`*
    -   `git reset \--soft HEAD\~1`: reset the last commit but not the records or changes made to the working directory

-   `git revert HEAD\~1`: is the safe git reset option for undoing a git commit. It does not revert a project to its previous state by removing all subsequent commits. In Git, this is called git reset.

# Git push

-   `git push origin main`: is used to push committed changes to remote repositories for collaboration. This allows other team members to access the changes you have made
-   `git push origin branchname`: send files to another branch. In this case branchname is the name of the branch.
-   `git push \--set-upstream origin branchname`: set a branch as default. Then you do not need to specify the branch you are pushing the commits

# Branches

A branch is a pointer to a specific commit SHA. You just have to be clear about which commit you want to point (see `git commit`, `git pull` or `git reset`).

`r emo::ji("shocked")` *Don't ask why you create a branch using `git checkout`*

-   `git checkout -b branchname`: create a new branch and switch to it. Branches are created to work in parallel. The main branch is the default branch when we create a repository. The idea is to create branches during development work so that everyone can work on their own and merge them into the main branch when we are done
-   `git branch branchname`: create a new branch but NOT check out the branch
-   `git checkout main`: return to the main branch. `r emo::ji("danger")` *Note that if you check out from one branch to another without committing first, all your changes will be overwritten*
-   `git branch -d branchname`: delete the branch named branchname from you pc
-   `git push origin \--delete branchname`: delete the remote branch named branchname (e.g. from GitHub). Note that the local and remote branch have nothing to do with each other so they must be removed separately
-   `git branch -a`: show all local and remote branches and tells you which branch you are on
-   `git branch \--show current`: in which branch you are
-   `git show-branch`: show the branches and their commits

# Git pull

-   `git pull`: update the local repository with the remote repository. It will update and merge to the latest commit. When working in a team is recommended to always start with `git pull` to work on the latest version.
-   `git fetch origin`: secure version of git pull. Does not merge files when updating with the remote repository.

# Git merge/conflicts

-   `git merge feature-branch`: supposing you have checked out the main branch, merge a feature branch. But sometimes git will find conflicts when merging and you will have to fix them manually. Git will show you where the conflicts are like this: \<\<\<\<\<\<code from main=======code from feature-branch\>\>\>\>\>\>. To solve this:

    1.  Edit the files

    2.  `git add` the fixed files

    3.  Using `git diff \--check` you can check for more conflicts

    4.  `git commit` and `git push` when done

`r emo::ji("voltage")` *Note that merge commits have two parents*

# Git ignore

-   `git status \--ignored`: return ignored files in the repository
-   `nano .gitignore`: \*.dat: ignore all files with that ending; !final.dat: except that one; results/: all results files, etc.
-   `git add -f file.dat`: force git add something that you have ignore it

# Some additional commands

-   `nano filename.txt`: create a file named filename.txt. It'll open a window so you can add the text. `ctrl x` to exit
-   `echo "filename text" \> filename.txt`: create a file named filename.txt and add the text filename text
-   `touch filename`: create a new file in a repository. Then go to nano and add text (same as using nano directly)
-   `cat filename.txt`: show the content of filename.txt
-   `git restore filename.txt`: delete the changes, restore them, of filename.txt
-   `history`: show the previous commands used
-   `clear`: refresh it
-   `cd \~`: go back to your home directory
-   `rmdir`: remove a directory
-   `rm filename`: remove a file
-   `cp filename`: copy a file
-   `mv filename /directoryname`: move a file
-   `grep wordtofind filename`: ctrl f in Windows
-   `grep -ic wordtofind filename`: count how many times a word appears
-   use the right click of the mouse to copy in the terminal

# Some interesting links

-   [Git Reference Manual](https://git-scm.com/docs)

-   [Software Carpentry: An introduction to version control for novices using Git](http://swcarpentry.github.io/git-novice/)

-   [Happy Git and GitHub for the useR](https://happygitwithr.com/)

-   [Atlassian Bitbucket](https://www.atlassian.com/git/tutorials)

-   [Oh Shit, Git!?!](https://dangitgit.com/)

-   [git - la guía sencilla por Roger Dudler](https://rogerdudler.github.io/git-guide/index.es.html)

-   [Apply for an educator or researcher discount](https://docs.github.com/en/education/explore-the-benefits-of-teaching-and-learning-with-github-education/apply-for-an-educator-or-researcher-discount)

------------------------------------------------------------------------

<details>

<summary>

Session Info

</summary>

```{r session-info}
Sys.time()
git2r::repository()
sessionInfo()
```

</details>
